# -*- coding: utf-8 -*-
"""Section 4 (cousin) and Section 5 (husband)."""
from reportlab.lib.units import inch
from reportlab.platypus import Spacer, PageBreak
from render import *

def cousin_steps():
    return [
        PageBreak(), H1('4. The cousin: itemized steps'),
        P('You are the engine of this plan: the organizer now, the paid attendant later, and the person whose documentation protects everyone\'s hours. '
          'Your two legal identities must stay separate: <b>helper with the paperwork</b> (Form H1003 authorized representative, medical power of attorney) is fine; '
          '<b>CDS Designated Representative</b> (Form 1720) is not, because a DR and the DR\'s spouse can never be paid by that employer (26 TAC 264.205; Form 1726).'),
        callout('HHSC Form 1726 (April 2026) says a CDS service provider may not be "the primary caregiver in Primary Home Care (PHC), Community Attendant Services (CAS) or Family Care (FC)." '
                'Form 1583 (April 2026) explains what that means: "any caregiver not eligible for hire under the CCAD unmet need policy," which is CCSE Handbook 2433. That policy is <b>task by task</b>: the caseworker decides for each task whether a household member is already meeting the need (coded "C", not purchased) or whether it is unmet (coded "P", purchased). '
                'You can be hired for every purchased task; the "do not hire" list is closed (the spouse, a parent of a minor, people with APS findings, unwilling household members), and "beyond these limitations, the caseworker will not specify who cannot be hired." '
                'Two things follow. First, at the Form H2060 visit, say plainly that you are not available as an unpaid caregiver and will provide care only as the paid attendant, so tasks are coded "P". '
                'Second, <b>CCSE 2433.2 has a 30-day rule:</b> a caregiver who quits a job to provide care is treated as available for hire only if HHSC verifies she left the job within 30 calendar days before or after the application date. Time your resignation to land inside that window and keep the separation letter. STAR+PLUS HCBS and CFC have no primary-caregiver line at all.', 'warn', 'The one rule that can block CAS pay, and exactly how to handle it'),
        H2('Phase A: Before you move (this week)'),
        steps_table([
            (1, 'Confirm you are hireable.', '18+; Social Security number and I-9 documents; a Texas DPS criminal history with no bar under Health and Safety Code 250.006; not on the Nurse Aide Registry (revoked), Employee Misconduct Registry, HHSC-OIG or federal exclusion lists. The FMSA runs these checks (Forms 1725, 1729); you do not.', 'Day 1'),
            (2, 'Get the paperwork authority, not the DR role.', 'Have the aunt and uncle each sign HHSC <b>Form H1003</b> (Appointment of an Authorized Representative) and a HIPAA release so HHSC, the caseworker and the MCO will talk to you. Medical Power of Attorney naming you is fine too. <b>Do not</b> sign Form 1720 as DR.', 'Day 1 to 7'),
            (3, 'Drive Steps 1 to 8 of Section 3 for both of them.', 'Interest list (844-438-5658, fallback 877-438-5658, plus YourTexasBenefits referral), Community Care intake (2-1-1 option 2), Form H1200 online, doctor visits for Form 3052, financial snapshot, VA intent to file. Keep the call log.', 'Day 1 to 7'),
            (4, 'Time the job separation, and put your status in writing.', 'If you are leaving a job to do this, resign within <b>30 calendar days before or after</b> the date the CAS application is filed (CCSE 2433.2) and keep the employer\'s separation letter; HHSC verifies it. Send a short letter to the regional Community Care office (via 2-1-1 or the ADRC, 855-937-2372): "I am relocating to be hired as the paid CDS attendant for my aunt and uncle. I am not available to provide unpaid care." Keep a copy for the H2060 visit.', 'Within 30 days of the application date'),
            (5, 'Make the house your legal home.', 'Driver\'s license, voter registration, mail. This is what makes the IRS Notice 2014-7 income exclusion available (you must live in the care recipient\'s home as your own home).', 'Move-in week'),
            (6, 'No rent. No cash. No deed changes.', 'Sign a written household-expense-sharing agreement (your share of utilities, groceries, repairs paid straight to the vendors). Rent to the aunt and uncle is countable income to them; gifts or paying you under the table create a Medicaid transfer penalty of $262.37 per day.', 'Move-in week'),
        ]),
        H2('Phase B: The assessment and hiring (Days 7 to 45)'),
        steps_table([
            (7, 'Be the informant at every assessment.', 'Bring a 7-day diary per spouse, the medication list, the PCP letter. For each of the 23 tasks on Form H2060 give minutes and frequency on the worst days. Ask for protective supervision hours (HCBS) if there is dementia.', 'Day 7 to 21'),
            (8, 'Complete the FMSA new-hire packet for EACH employer.', 'Form 1724 cover sheet, <b>1725</b> (background/registry consent), <b>1734</b> (relationship certification: every answer "No"), 1727, 1728 (workers\' comp election), <b>1730</b> (wage plan), 1731 (schedule), 1732 (training log), 1733 (if delegated health tasks), 1737 (employer-employee agreement), I-9, W-4, direct deposit. Two files: one for the aunt, one for the uncle. Nobody works until the FMSA returns Form 1729 and approves the budget in writing.', 'Up to 3 weeks after the FMSA meeting'),
            (9, 'Negotiate the wage to the ceiling.', 'Ask the FMSA for the budget workbook. On 2026 rates the ceiling is about <b>$15.05/hour under CAS</b> ($16.33 rate) and about <b>$15.90/hour under STAR+PLUS HCBS</b> ($17.24 rate) if nothing is reserved for benefits. At least 66.36% of the budget must go to employee compensation. Put remainder into accrued paid leave, a longevity bonus, health-premium reimbursement (non-taxable) or workers\' comp (26 TAC 264.505). Unused money is forfeited to the state.', 'Before first shift'),
            (10, 'Set a schedule that avoids overtime.', 'Overtime over 40 hours for one employer is paid at 1.5x out of the same fixed budget, which forces the hourly wage down. Best pattern: you work up to 40 hours for one spouse and the husband works up to 40 for the other; the remaining authorized hours (up to 50 each) are covered by the other person. Ask the FMSA in writing how it treats combined hours across the two employers and whether it recognizes the live-in domestic worker overtime exemption (29 CFR 552.102).', 'Before first shift'),
            (11, 'Ask the FMSA two tax questions in writing.', '(a) "Do you apply IRS Notice 2014-7 to live-in caregivers and report excluded wages in W-2 Box 12 Code II?" (b) "Do you apply it to CAS/PHC pay or only to STAR+PLUS HCBS pay?" See Section 6.7.', 'Before first payroll'),
        ]),
        H2('Phase C: Working (ongoing)'),
        steps_table([
            (12, 'Clock every shift in EVV.', 'Install HHAeXchange+ (support 833-430-1307). Clock in at the start and out at the end of each authorized shift, separately for the aunt and for the uncle, never overlapping. There is no live-in exemption. Fix any missed clock within <b>95 days</b> or the pay is gone. Overnight shifts split automatically at midnight.', 'Every shift'),
            (13, 'Work the authorized schedule and tasks only.', 'Form 1731 schedule equals the authorized units. Being present in the home is not billable; assessed tasks are. Keep a daily task log per spouse (Form 1720 service log) that matches EVV.', 'Every day'),
            (14, 'Protect and grow the hours.', 'Request a reassessment after any hospitalization, fall or decline. Appeal low hours within 90 days (CAS, CCSE 2900) or 60 days to the MCO (STAR+PLUS). To keep hours during the appeal: CAS, request before the effective date on Form 2065-A; STAR+PLUS, within 10 days of the MCO notice (42 CFR 438.420). Managed Care Ombudsman 866-566-8989 for MCO stalls.', 'As needed'),
            (15, 'Build the training file (Section 8).', 'AAA caregiver program (800-252-9240), dementia training, CPR, the CNA course if you want it. Log everything on Form 1732; it justifies the top wage and protects you in any audit.', 'First 90 days'),
            (16, 'Do the taxes right.', 'Your pay is subject to Social Security and Medicare tax (you earn credits) and Texas unemployment coverage (Labor Code 201.065 excludes only a spouse, a parent working for a child, or a child under 21 working for a parent). If the FMSA applies Notice 2014-7, your federal income tax on that pay is zero and you can still elect to count it as earned income for the Earned Income Tax Credit. Check your health-coverage plan: excluded pay is not in MAGI, and a household with only excluded income can fall into Texas\'s coverage gap (below 100% of poverty, no marketplace subsidy).', 'Each January'),
            (17, 'When the STAR+PLUS HCBS release comes, move with it.', 'Same FMSA if it is in the MCO\'s network; new Forms 1584/1735; new budget at $17.24/hour; ask for protective supervision hours and in-home respite (delivered by an outside person, see Section 5).', 'Months 3 to 12'),
        ]),
    ]

def husband_steps():
    return [
        PageBreak(), H1('5. The husband: itemized steps'),
        P('The husband is the second paid attendant, the required backup, the record-keeper, and, if either spouse is a veteran, the person who runs the VA side. '
          'Two things he cannot be: the CDS Designated Representative while his wife is paid by that employer (the DR\'s spouse may not be an employee), and a paid STAR+PLUS HCBS respite provider while living in the home '
          '(STAR+PLUS Handbook 7300: the in-home respite provider "must not live with the member").'),
        steps_table([
            (1, 'Get hired as the second CDS employee.', 'Same new-hire packet as the cousin (Forms 1724, 1725, 1734, 1728, 1730, 1731, 1732, 1737, I-9, W-4). Nothing in 26 TAC 264 or Form 1726 bars a niece\'s husband. If he will drive either person, a Texas driver\'s license and auto insurance card go in the file (26 TAC 264.231).', 'Days 21 to 45'),
            (2, 'Take the other spouse.', 'Cleanest structure: cousin is the primary attendant for one spouse, husband for the other, each up to 40 hours with that employer, and each picks up the other spouse\'s remaining hours (up to 50). This uses every authorized hour, avoids overtime, and keeps EVV visits from overlapping.', 'At scheduling'),
            (3, 'Be the named backup on Form 1740.', 'CDS requires a Service Backup Plan for critical services. He is the backup for her shifts and she for his; sick days and appointments are covered without losing hours.', 'At enrollment'),
            (4, 'If one spouse cannot be their own employer, solve the DR problem without him.', 'The aunt can be the uncle\'s DR and the uncle the aunt\'s (a spouse may be DR; a spouse just cannot be the paid attendant). If neither can, use a relative or friend who lives elsewhere. Whether he can be DR for the uncle while his wife is paid only by the aunt is legally arguable under 264.205 but has not been ruled on; do not rely on it.', 'Before CDS forms'),
            (5, 'Own the VA file if there is a veteran (Section 6.8).', 'Texas Veterans Commission 800-252-8387 for a free accredited claims advisor; VA Form 21-0966 intent to file first; physician completes 21-2680; 21P-527EZ with 21P-8416 medical expense report; enroll the veteran in VA health care (10-10EZ) and ask the VA social worker about Veteran-Directed Care, Homemaker/Home Health Aide hours and respite. If the veteran is 70%+ service-connected, file 10-10CG for the caregiver stipend with the cousin as Primary Family Caregiver and himself as Secondary.', 'Week 1 onward'),
            (6, 'Keep the ledger that protects the money.', 'Monthly: how every VA Aid and Attendance dollar was spent (medications, supplies, equipment, private-pay care hours outside the Medicaid plan), receipts for care and home costs (future MERP deduction under 1 TAC 373.213), copies of every notice with its appeal deadline, the QIT statements if he is trustee.', 'Monthly'),
            (7, 'Run home safety and equipment.', 'CDC STEADI home checklist, DME orders through the PCP and MCO, minor home modification bids ($7,500 lifetime per spouse under HCBS), ERS pendant, smoke and CO detectors, clear paths, grab bars, lighting.', 'First 60 days and ongoing'),
            (8, 'Run logistics.', 'Medical transportation (MCO line or 877-633-8747; 2 workdays\' notice) or drive under the Individual Transportation Participant mileage program; pharmacy; DAHS or outside respite scheduling; the AAA respite voucher provider (must be someone outside the household).', 'Ongoing'),
            (9, 'Watch for burnout and schedule the breaks.', 'Use the STAR+PLUS HCBS respite days (delivered by an outside provider), AAA vouchers, and adult day services. Caregiver Action Network 855-227-3640; 988 any time.', 'Monthly'),
            (10, 'Keep outside income in view.', 'If he keeps any outside work, that taxable income keeps the household above 100% of the poverty line for marketplace health-insurance subsidies (Texas did not expand Medicaid) and may bring employer coverage. Weigh that against the paid attendant hours he can fill; the numbers are in Section 6.', 'Decide in month 1'),
        ]),
        callout('The husband CAN be paid as the second attendant for CAS, PHC, CFC and STAR+PLUS HCBS attendant hours. He CANNOT be paid for STAR+PLUS HCBS respite while he lives in the home, cannot be the AAA voucher respite worker, and cannot be the DR for an employer that pays his wife. Plan around those three lines and every other hour is open to him.', 'info', 'Summary for the husband'),
    ]
