# -*- coding: utf-8 -*-
"""Section 10: directory, MCOs, forms, rules, search terms, glossary."""
from reportlab.lib.units import inch
from reportlab.platypus import Spacer, PageBreak
from render import *

def directory():
    return [
        PageBreak(), H1('10. Directory: who to call, what to say, where to look'),
        P('Every number below was checked against an official page or the organization\'s own published materials on September 3, 2026. Numbers still change; read plan numbers off the Medicaid ID card once issued, and use 2-1-1 as the fallback for any HHSC line.'),
        H2('10.1 Texas HHSC and Medicaid'),
        table(['Who', 'Number / site', 'Hours', 'Say this / use it for'], [
            ['2-1-1 Texas (HHSC benefits line)', '<b>2-1-1, option 2</b>; 877-541-7905 from out of state or if 2-1-1 fails', '2-1-1 is 24/7', '"I want to apply for Medicaid for the Elderly and People with Disabilities and Community Attendant Services for two people; please open a Community Care intake for each and note we want Consumer Directed Services." Also: application status, paper Form H1200, report changes.'],
            ['YourTexasBenefits.com', 'yourtexasbenefits.com', '24/7', 'File Form H1200 online, upload documents, check status, "Find Support Services" referral to the interest list. Ask for Form H1800 receipt to prove the filing date.'],
            ['STAR+PLUS HCBS interest list', '<b>844-438-5658</b> (STAR+PLUS HCBS line, CCSE Handbook 2230, rev. June 2026); 877-438-5658 (HHSC general interest-list line) as fallback', 'Business hours', '"Please add [name] to the STAR+PLUS HCBS interest list and confirm the request date." Update address and phone here.'],
            ['Aging and Disability Resource Center (statewide)', '<b>855-937-2372</b> (855-YES-ADRC)', 'Business hours', 'Options counseling; help finding the regional Community Care office; Take Time Texas respite.'],
            ['Area Agencies on Aging / HICAP (Texas SHIP)', '<b>800-252-9240</b>', 'Business hours', 'Caregiver support program, respite vouchers, free Medicare/MSP/Extra Help counseling, help with Form H1200.'],
            ['Texas Medicaid Enrollment Broker (plan choice)', '<b>800-964-2777</b>; STAR+PLUS members routed to <b>877-782-6440</b>', 'Not published', 'Which STAR+PLUS plans serve your county; change plans (as often as monthly).'],
            ['HHS Office of the Ombudsman, Managed Care', '<b>866-566-8989</b>; fax 888-780-8099; online heartbep-ext.hhs.state.tx.us', 'Mon-Fri 8-5', 'MCO not assessing, low hours, CDS/FMSA disputes. Call the plan first, then here.'],
            ['HHS Office of the Ombudsman, general', '<b>877-787-8999</b>', 'Not published', 'MEPD application past 45 days; caseworker or interest-list problems.'],
            ['HHSC Complaint and Incident Intake', '800-458-9858; tulip.hhs.texas.gov/LTCcomplaint', 'Mon-Fri 7-7', 'Complaints about licensed agencies and facilities (not MCOs).'],
            ['HHSC Office of Inspector General fraud line', '800-436-6184; oig.hhs.texas.gov/reportfraud', 'Not published', 'Fraud by providers; also the office that audits EVV and timesheets.'],
            ['Medicaid Estate Recovery Program', '<b>800-641-9356</b>; merp@hhs.texas.gov (contractor changes to Stellarware Sept. 1, 2026; number may change)', 'Not published', 'How CAS and STAR+PLUS HCBS costs affect the home; hardship waiver criteria; Form 5006.'],
            ['TMHP (Texas Medicaid and Healthcare Partnership)', '800-925-9126; LTC line 800-626-4117', 'Mon-Fri 7-7 CT', 'Medicaid ID and eligibility verification; MN/LOC form processing.'],
            ['Medical Transportation Program (fee-for-service members)', '877-633-8747 (877-MED-TRIP)', 'Mon-Fri 8-5', 'Rides or mileage; STAR+PLUS members call the plan\'s transportation line instead.'],
            ['HHSC Consumer Directed Services policy', 'CDS@hhs.texas.gov; HHSC main 512-424-6500', 'Business hours', 'CDS rule questions; FMSA complaints that the caseworker cannot fix.'],
            ['FMSA directory (CAS/PHC/FC)', 'resources.hhs.texas.gov/fmsa/PHC', '24/7', 'Search FMSAs by county (26 statewide for PHC/CAS/FC); for STAR+PLUS ask the plan for its FMSA list.'],
            ['HHAeXchange (EVV) Texas support', '<b>833-430-1307</b>; TXSupport@hhaexchange.com', 'Business hours', 'App login, clock in/out problems, visit maintenance.'],
            ['HHSC Provider Finance (rates)', '737-867-7817; PFD-LTSS@hhs.texas.gov', 'Business hours', 'Current CDS and attendant rate tables.'],
            ['HHSC Employability Status Check (registries)', 'txhhsregulatory.my.site.com/EMR', '24/7', 'The FMSA runs Nurse Aide, Medication Aide and Employee Misconduct Registry checks here.'],
            ['Adult Protective Services (Texas Abuse Hotline)', '<b>800-252-5400</b>; txabusehotline.org', '24/7', 'Abuse, neglect, self-neglect, exploitation of an adult at home. Reporting is mandatory.'],
            ['Long-Term Care Ombudsman', '800-252-2412', 'Not published', 'Facility residents only (rehab stays, out-of-home respite, nursing-home discharge pressure).'],
        ], [1.5 * inch, 1.75 * inch, 0.75 * inch, 2.9 * inch]),
        H2('10.2 STAR+PLUS health plans by service area (HHSC chart effective Sept. 1, 2024; unchanged as of Sept. 2026)'),
        table(['Plan', 'Service areas', 'Member services'], [
            ['Superior HealthPlan', 'Dallas, Hidalgo, Lubbock, Nueces, Travis, MRSA Central, MRSA West', '877-277-9772 (Mon-Fri 8-5)'],
            ['Molina Healthcare of Texas', 'Bexar, Dallas, El Paso, Harris, Hidalgo, Jefferson, Tarrant, MRSA Northeast', '866-449-6849 (Mon-Fri 8-6 CT)'],
            ['UnitedHealthcare Community Plan', 'Bexar, Dallas, Harris, Hidalgo, Tarrant, Travis, MRSA Central, MRSA Northeast', '888-887-9003; LTSS line 888-787-4107'],
            ['Wellpoint (formerly Amerigroup)', 'Jefferson, Lubbock, Nueces, MRSA West', '833-731-2160 (Mon-Fri 7-6 CT)'],
            ['Community First Health Plans', 'Bexar (San Antonio region)', '855-607-7827 / 210-358-6403'],
            ['Community Health Choice', 'Harris (Houston region, 9 counties)', '888-435-2850 / 713-295-2300 (Mon-Fri 8-5)'],
            ['El Paso Health', 'El Paso and Hudspeth counties', '833-742-3127 (Mon-Fri 8-5 MT)'],
        ], [1.8 * inch, 3.1 * inch, 2.0 * inch]),
        P('Aetna Better Health, Blue Cross Blue Shield of Texas and FirstCare do not hold STAR+PLUS contracts even though an older HHSC logo page still shows them. Choose the plan by calling each service-coordination line and asking: "Which FMSAs are in your network? How fast do you complete the H2060 for new members? Do you authorize protective supervision?" You can switch plans monthly.', 'small'),
        H2('10.3 Federal, VA, legal and caregiver-support contacts'),
        table(['Who', 'Number / site', 'Hours', 'Use it for'], [
            ['Social Security Administration', '800-772-1213 (TTY 800-325-0778)', 'Mon-Fri 8-7', 'Benefit verification letters for the H1200; Extra Help; the cousin\'s wage record.'],
            ['Medicare', '800-633-4227 (TTY 877-486-2048)', '24/7', 'Home health, DME, hospice; confirm Part B premium stops after QMB.'],
            ['IRS', '800-829-1040; irs.gov Notice 2014-7 Q&amp;A', 'Mon-Fri 7-7 local', 'Difficulty-of-care exclusion; W-2 Box 12 Code II; EITC election.'],
            ['U.S. Department of Labor, Wage and Hour', '866-487-9243', 'Business hours', 'Live-in domestic worker overtime rules.'],
            ['Texas Workforce Commission (unemployment)', '800-939-6631; twc.texas.gov', 'Mon-Fri 8-6 CT', 'Claims if CDS employment ends.'],
            ['Texas Veterans Commission / Texas Veterans Call Center', '<b>800-252-8387</b> (800-252-VETS)', 'Mon-Fri 7:30-5:30 CT', 'Free accredited claims advisor for pension, A&amp;A, PCAFC.'],
            ['VA Benefits (pension status)', '800-827-1000 (the older 877-294-6380 no longer appears on va.gov)', 'Mon-Fri 8am-9pm ET', 'Pension and A&amp;A claim status; Pension Intake Center, PO Box 5365, Janesville WI 53547-5365.'],
            ['VA Caregiver Support Line', '855-260-3274', 'Mon-Fri 8-8 ET', 'PCAFC (Form 10-10CG), Caregiver Support Coordinator, respite.'],
            ['VA Health Benefits (enrollment)', '877-222-8387', 'Mon-Fri 8-8 ET', 'Form 10-10EZ; find the VA medical center; Veteran-Directed Care referral via the social worker.'],
            ['Legal Hotline for Texans (Texas Legal Services Center)', '<b>800-622-2520, option 3</b>; texaslawhelp.org', 'Mon-Fri 8:30-5', 'Free advice for 60+: POA, TODD, Medicaid, MERP. Free forms at TexasLawHelp.org.'],
            ['Texas RioGrande Legal Aid / Lone Star Legal Aid / Legal Aid of NorthWest Texas', '833-329-8752 / 800-733-8394 / 888-529-5277', 'Business hours', 'Free civil legal aid by region.'],
            ['State Bar of Texas Lawyer Referral', '800-252-9690; texasbar.com/lris', 'Mon-Fri 8:30-4:30', 'Elder-law attorney for the QIT, care agreement, application staging. Also the Texas NAELA directory at naela.org.'],
            ['Alzheimer\'s Association', '800-272-3900', '24/7', 'Dementia care coaching, classes, support groups.'],
            ['Caregiver Action Network help desk', '855-227-3640', 'Mon-Fri 7-6 CT', 'Caregiver coaching.'],
            ['988 Suicide and Crisis Lifeline', 'Call or text 988', '24/7', 'Caregiver crisis or burnout.'],
            ['Eldercare Locator', '800-677-1116', 'Business hours', 'National referral to the local AAA/ADRC and Veteran-Directed Care sites.'],
            ['Acentra Health (Texas Medicare QIO)', '888-315-0636', 'Business hours', 'Fast appeal of a hospital discharge before home supports are ready.'],
            ['Prometric (Texas nurse aide exam)', '800-488-5787', 'Business hours', 'CNA written and skills exam scheduling.'],
            ['Texas Lifeline (phone discount)', '866-454-8387', 'Business hours', 'Lifeline application once Medicaid or SNAP is approved.'],
            ['Texas Comptroller property tax help', '800-252-9121; comptroller.texas.gov', 'Business hours', 'Over-65 homestead exemption (Form 50-114), tax ceiling, deferral (Form 50-126).'],
        ], [1.75 * inch, 1.9 * inch, 0.95 * inch, 2.3 * inch]),
        H2('10.4 Forms you will hear about, by number'),
        table(['Form', 'What it is', 'Who handles it'], [
            ['H1200 / H1200-EZ', 'Medicaid (MEPD) application; EZ version for Medicare Savings Programs only', 'Aunt and uncle (organizer); YourTexasBenefits.com'],
            ['H1003', 'Appointment of an Authorized Representative for HHSC dealings', 'Aunt and uncle name the cousin'],
            ['H1020', 'HHSC request for missing information; final due date is day 39', 'Answer immediately'],
            ['H1746-A', 'MEPD referral cover sheet routing the H1200 and waiver status', 'HHSC staff'],
            ['3052', 'Practitioner\'s Statement of Medical Need (CAS/PHC)', 'The doctor'],
            ['2110 / 2060 (H2060) / H2060-A / H2060-B', 'Community Care intake; the needs assessment and task/hour guide that sets weekly hours; STAR+PLUS addenda', 'Caseworker or MCO nurse, with the family as informant'],
            ['2101 / 2065-A', 'Authorization of Community Care services; notice of decision and hours (appeal rights)', 'Caseworker; watch the mail'],
            ['1581 / 1582 / 1583 / 1584', 'CDS overview; CDS responsibilities and self-assessment; employee qualification requirements; choice of CDS, SRO or agency and the FMSA', 'Aunt and uncle sign'],
            ['1720 / 1721', 'Appointment / revocation of a Designated Representative (never the cousin or husband)', 'Aunt and uncle'],
            ['1722', 'EVV responsibility option (1, 2 or 3)', 'Employer'],
            ['1724 / 1725 / 1729', 'New-hire packet cover; background and registry check consent; FMSA applicant verification (no work before it is signed)', 'Cousin, husband, FMSA'],
            ['1726 / 1734', 'Relationship definitions and certification of relationship status (every answer "No")', 'Employer and each employee'],
            ['1728', 'Liability acknowledgment / workers\' compensation election', 'Employer'],
            ['1730 / 1731 / 1732 / 1733 / 1737', 'Wage and benefits plan; work schedule; training log; nursing-licensure exemption for delegated tasks; employer-employee agreement', 'Employer and employee'],
            ['1735 / 1736 / 1740', 'Employer-FMSA service agreement; orientation record; service backup plan', 'Employer and FMSA'],
            ['H2053-B / H3676 / H1700-1 / H2065-D / H2118', 'STAR+PLUS plan choice; pre-enrollment assessment authorization (45-day clock); Individual Service Plan; notice of managed-care services (start date, appeal rights); interest-list continued-interest confirmation (30 days)', 'Enrollment broker, MCO, HHSC Program Support Unit'],
            ['MN/LOC', 'Medical Necessity and Level of Care assessment (TMHP portal), physician-signed; sets the 202% cost ceiling', 'MCO nurse and the doctor'],
            ['H1272 / H1275', 'Spousal resource assessment; expanded SPRA request', 'MEPD specialist, if staging applications'],
            ['8001 / 5006', 'MERP notice of intent to file a claim; hardship waiver application (60 days)', 'Estate representative, later'],
            ['1240', 'HHSC request to the VA for the benefit breakdown (A&amp;A vs base pension)', 'MEPD specialist'],
            ['H1010 / H0011', 'SNAP application; Texas Simplified Application Project for all-elderly households', 'Aunt and uncle'],
            ['50-114 / 50-126', 'Homestead exemption application; over-65 tax deferral affidavit', 'County appraisal district'],
            ['VA 21-0966 / 21-22 / 21P-527EZ / 21-2680 / 21P-8416 / 21P-0969 / 10-10EZ / 10-10CG / 10-10EC', 'Intent to file; VSO representation; pension application; A&amp;A physician exam; medical expense report; income/asset statement; VA health enrollment; PCAFC; extended-care copay', 'Veteran, with TVC advisor'],
            ['IRS W-2 Box 12 Code II; Schedule 1 line 8s', 'Where excluded Medicaid waiver pay is reported', 'FMSA and the cousin\'s tax preparer'],
        ], [1.9 * inch, 3.3 * inch, 1.7 * inch]),
        H2('10.5 Rules to cite in a letter or appeal'),
        table(['Citation', 'What it governs'], [
            ['1 TAC 353.1153', 'STAR+PLUS HCBS eligibility, interest list, 202% cost limit'],
            ['1 TAC 354.1360-354.1366', 'Community First Choice'],
            ['1 TAC 355.7052 (and repealed 355.7051)', 'Attendant rate methodology; former $10.60 base wage'],
            ['1 TAC Chapter 357', 'Fair hearings'],
            ['1 TAC Chapter 358 (358.433, 358.437)', 'MEPD financial eligibility; special income limit; couple budgets'],
            ['1 TAC Chapter 373 (373.105, 373.209, 373.213)', 'Estate recovery: scope, hardship waivers, deductions'],
            ['26 TAC Chapter 264 (264.205, 264.223, 264.225-.233, 264.241, 264.403, 264.505-.511)', 'Consumer Directed Services: DR, liability, hiring checks, overtime, FMSA transfer, budgets'],
            ['26 TAC Chapter 271 (271.5, 271.53, 271.69, 271.71, 271.77, 271.81, 271.151)', 'Community Care eligibility: interest lists, income, Family Care, meals, DAHS, PHC/CAS, case timelines'],
            ['22 TAC Chapter 225', 'What an unlicensed attendant may do under RN delegation'],
            ['Tex. Est. Code ch. 114; 752.051; 1104.202; 1357', 'Transfer on Death Deed; durable POA; declaration of guardian; supported decision-making'],
            ['Tex. Health &amp; Safety Code 166.154, 181.154, 250.006', 'Medical POA; HIPAA authorization; criminal-history bars'],
            ['Tex. Labor Code 201.065; Tex. Tax Code 11.13, 11.26, 33.06', 'Unemployment family exclusion; homestead exemptions, ceiling, deferral'],
            ['IRS Notice 2014-7; IRC 131; 26 USC 3121(b)(3); Feigh v. Commissioner, 152 T.C. No. 15', 'Difficulty-of-care exclusion; FICA family exemptions; EITC election'],
            ['29 CFR 552.102; 29 CFR 785.22', 'Live-in domestic worker overtime exemption; sleep time'],
            ['38 CFR 3.274-3.278; 38 CFR 71.15-71.40; 38 U.S.C. 1720G', 'VA pension net worth, transfers, medical expenses; PCAFC'],
            ['Handbooks: MEPD (A-4100, B-6400, E-3000, E-4300, E-7100, F-3600, F-4200, G-4100, G-6200, I-3100, I-4100, I-5100, J-1300, O-1000, Q-2500, App. XXXI, XXXVI); CCSE (2300, 2400, 2531, 2900, 3200, 4400, 4600, 6300); STAR+PLUS (1100, 3200, 3400, 6100-6600, 7300, 8200); PSU (1200, 3311, 4200, 7200); EVV (7000, 9000, 17000)', 'All at fhb.hhs.texas.gov/handbooks'],
        ], [3.2 * inch, 3.7 * inch]),
        H2('10.6 Search terms that reliably find the official page'),
        bullets([
            '"STAR+PLUS HCBS interest list" hhs.texas.gov; "interest list reduction" hhs.texas.gov; "1 TAC 353.1153"',
            '"Community Attendant Services" CCSE Handbook 4600; "26 TAC 271.81"; "Form 3052 practitioner\'s statement of medical need"',
            '"Form H2060 needs assessment questionnaire task hour guide"; "CCSE Handbook 2441.3 companion case"',
            '"Consumer Directed Services" "How CDS Works" hhs.texas.gov; "CDS FAQ" hhs.texas.gov pdf; "Form 1726 relationship definitions CDS"; "26 TAC 264.205 designated representative"; "Form 1730 wage and benefits plan"; "PHC CDS budget workbook"',
            '"FMSA agencies" resources.hhs.texas.gov/fmsa; "CDS support advisors" resources.hhs.texas.gov',
            '"9-1-2025 PHC rates" pfd.hhs.texas.gov; "9-1-2025 STAR+PLUS rates" pfd.hhs.texas.gov; "Rider 23 attendant wage $13.00 Information Letter 2025-11"',
            '"MEPD Handbook Appendix XXXI budget reference chart"; "MEPD Appendix XXXVI qualified income trust"; "MEPD I-5100 transfer of assets divisor"; "MEPD I-4100 compensation"; "MEPD J-1300 spousal definitions"',
            '"Your Guide to the Medicaid Estate Recovery Program" hhs.texas.gov; "1 TAC 373.213"; "Transfer on Death Deed kit" texaslawhelp.org',
            '"STAR+PLUS Handbook 7300 respite"; "STAR+PLUS Handbook 6400 adaptive aids"; "STAR+PLUS Handbook 6600 minor home modifications"; "STAR+PLUS Handbook 8200 consumer directed services"',
            '"EVV policy handbook 9000 visit maintenance 95 days"; "HHAeXchange Texas CDS employer"',
            '"STAR+PLUS health plans by service area" pdf hhs.texas.gov; "Ombudsman managed care help" hhs.texas.gov',
            '"certain Medicaid waiver payments may be excludable from income" irs.gov; "Feigh v. Commissioner AOD 2020-02"; "Fact Sheet 79B live-in domestic service workers" dol.gov',
            '"veterans pension rates" va.gov; "38 CFR 3.278"; "CCSE Handbook 2531 aid and attendance"; "MEPD E-4315 VA benefits"; "PCAFC eligibility" caregiver.va.gov; "Texas Veterans Commission claims"',
            '"Area Agencies on Aging" hhs.texas.gov; "respite voucher program guidelines" hhs.texas.gov; "Take Time Texas respite"; "NATCEP" hhs.texas.gov; "22 TAC 225 delegation"',
        ], 'small'),
        H2('10.7 Glossary'),
        table(['Term', 'Meaning'], [
            ['ADL / IADL', 'Activities of daily living (bathing, dressing, toileting, transfers, eating, walking) / instrumental activities (meals, cleaning, shopping, medications, escort)'],
            ['A&amp;A', 'VA Aid and Attendance, the highest tier of VA pension or a compensation add-on for people who need help with daily living'],
            ['CAS / PHC / FC', 'Community Attendant Services (Medicaid-funded attendant hours without full Medicaid) / Primary Home Care (same, for people with full Medicaid) / Family Care (state-funded backup)'],
            ['CCSE', 'Community Care Services Eligibility, the HHSC caseworker unit that runs CAS, PHC, FC, meals, DAHS'],
            ['CDS / FMSA / DR', 'Consumer Directed Services (the person is the employer) / Financial Management Services Agency (payroll agent) / Designated Representative (runs employer duties; cannot be paid or married to an employee)'],
            ['CFC', 'Community First Choice, an attendant benefit with no cap and no waitlist, available only to SSI-level Medicaid members'],
            ['EVV', 'Electronic Visit Verification: the required clock-in/clock-out for every attendant shift'],
            ['H2060 / MN/LOC / ISP', 'The needs assessment that sets hours / the medical necessity and level-of-care assessment for STAR+PLUS HCBS / the Individual Service Plan (Form H1700-1)'],
            ['MAO', 'Medical Assistance Only: the Medicaid group for people with income between the SSI level and 300% of SSI; most retirees'],
            ['MCO / service coordinator', 'The STAR+PLUS managed-care plan and its nurse or case manager who assesses and authorizes services'],
            ['MEPD', 'Medicaid for the Elderly and People with Disabilities, the HHSC financial eligibility unit'],
            ['MERP', 'Medicaid Estate Recovery Program'],
            ['MSP / QMB / SLMB / QI', 'Medicare Savings Programs that pay Medicare premiums and, for QMB, all cost-sharing'],
            ['PAS', 'Personal assistance services: attendant hours'],
            ['PCAFC', 'VA Program of Comprehensive Assistance for Family Caregivers (monthly stipend to the caregiver)'],
            ['PSU', 'HHSC Program Support Unit that processes STAR+PLUS HCBS eligibility'],
            ['QIT', 'Qualified Income Trust (Miller trust) used when income is over the $2,982 cap'],
            ['SPRA / MMMNA', 'Spousal Protected Resource Amount / Monthly Maintenance Needs Allowance for a community spouse'],
            ['STAR+PLUS HCBS', 'The Texas home-and-community-based waiver program for adults who meet nursing-facility level of care (formerly the STAR+PLUS Waiver)'],
            ['TODD', 'Transfer on Death Deed'],
        ], [1.5 * inch, 5.4 * inch]),
        Spacer(1, 10),
        P('Sources: Texas HHSC handbooks and forms at fhb.hhs.texas.gov (MEPD, CCSE, STAR+PLUS, PSU, CDS, EVV), HHSC Provider Finance rate schedules effective September 1, 2025, HHSC interest-list data through July 31, 2026, Texas Administrative Code, CMS Informational Bulletin of April 27, 2026, IRS Notice 2014-7 and Q&amp;A, VA pension rate tables effective December 1, 2025, OPM 2026 salary tables, Texas statutes. Research and cross-checking completed September 3, 2026. Rules change on September 1 and January 1 each year.', 'tiny'),
    ]
