# -*- coding: utf-8 -*-
"""Section 2 (programs) and Section 3 (aunt and uncle steps)."""
from reportlab.lib.units import inch
from reportlab.platypus import Spacer, PageBreak
from render import *

def programs():
    return [
        PageBreak(), H1('2. The programs, in plain English'),
        P('Texas has several programs that will pay for an attendant. Only some of them let the family be the attendant, and they differ enormously in hours, '
          'waitlists and extras. This is the map. Rule citations are included so you can quote them to a caseworker or in an appeal.'),
        table(['Program', 'Who runs it', 'Who qualifies', 'Hours and extras', 'Family can be paid?', 'Waitlist / speed'], [
            ['<b>Community Attendant Services (CAS)</b><br/>26 TAC 271.81; CCSE Handbook 4600; MEPD A-4100',
             'HHSC regional Community Care caseworker; MEPD does the money test',
             'Income up to $2,982/mo per person ($5,964 couple); resources $2,000 / $3,000; Form 3052 medical need; H2060 score 24+; 6+ hrs/week need',
             'Up to 50 hrs/week per person (42 if priority). Attendant tasks only. No Medicaid card.',
             'Yes, via CDS (Form 1584). Niece and husband eligible.',
             'No interest list. Home visit within 14 days; decision within 30 days.'],
            ['<b>STAR+PLUS HCBS</b> (the former STAR+PLUS Waiver)<br/>1 TAC 353.1153; STAR+PLUS Handbook',
             'A STAR+PLUS managed-care plan (MCO) and its service coordinator; HHSC Program Support Unit',
             'Age 21+; nursing-facility medical necessity (MN/LOC); same money limits; Qualified Income Trust if over income',
             'No weekly cap, no minimum score. Plus 30 days respite/yr, nursing, therapies, $10,000/yr adaptive aids, $7,500 home mods, $5,000/yr dental, meals, ERS, protective supervision hours for dementia',
             'Yes, via CDS for attendant hours, in-home respite, nursing, therapies',
             'Interest list; nearly everyone on it under 12 months as of July 2026. About 3 to 5 months from release to start of care.'],
            ['<b>Community First Choice (CFC)</b><br/>1 TAC 354.1360-.1366',
             'MCO (STAR+PLUS)',
             'Only people with SSI or "SSI-related" Medicaid (income near $994 single / $1,491 couple, or Pickle, disabled widow(er) categories). NOT available to the 300%-income "MAO" group most retirees fall in.',
             'No cap, no interest list; attendant hours, habilitation, ERS',
             'Yes, via CDS',
             'Immediate, but only if a spouse fits an SSI category. Check, then move on.'],
            ['<b>Primary Home Care (PHC)</b><br/>26 TAC 271.81',
             'MCO for STAR+PLUS members; caseworker otherwise',
             'Full Medicaid plus same functional test as CAS',
             'Up to 50 hrs/week. This is what CAS converts into once a person has full Medicaid.',
             'Yes, via CDS', 'No interest list'],
            ['<b>Family Care (Title XX)</b><br/>26 TAC 271.69; CCSE 4400',
             'HHSC caseworker',
             'Same income limit but resources up to $5,000 / $6,000; for people who fail the CAS resource test',
             'Up to 50 hrs/week', 'Yes, via CDS', 'Regional interest list. Get on it as a backup the same day.'],
            ['<b>Day Activity and Health Services (DAHS)</b><br/>26 TAC 271.77',
             'MCO or caseworker', 'Chronic diagnosis; physician orders (Form 3055)',
             'Adult day center up to 10 units/week, in addition to attendant hours', 'No (center staff)', 'Medicaid: none. Title XX: interest list'],
            ['<b>Adult Foster Care</b><br/>26 TAC 271.73',
             'Caseworker or MCO', 'Person cannot need "considerable" personal care',
             '$14.81/day (CCSE) or $19.19 to $67.20/day (HCBS). Cannot be combined with attendant hours.',
             'Provider lives in; a relative is not barred', '<b>Not worth it</b> for this family: 50 hours of CAS pays about $117/day.'],
            ['<b>PACE</b> (all-inclusive elder care)', 'PACE organization', 'Age 55+, nursing-home level, lives in a PACE zip code (El Paso, Amarillo, Lubbock areas)',
             'Everything, through the PACE center', 'Generally no', 'Only if in a PACE area'],
        ], [1.25 * inch, 0.95 * inch, 1.35 * inch, 1.35 * inch, 0.9 * inch, 1.1 * inch], font='cell'),
        Spacer(1, 6),
        callout('Most Social Security retirees have income above $994 a month, which puts them in the "Medical Assistance Only" (MAO) 300%-of-SSI group. '
                'In that group, CFC is NOT available (STAR+PLUS Handbook 1100 and 6118), so plan on CAS now and STAR+PLUS HCBS later. '
                'If either spouse\'s countable income is at or under $994 ($1,491 combined), apply for SSI first instead: it brings full Medicaid, STAR+PLUS, and CFC immediately, and skips the interest list.', 'warn', 'The single most important eligibility fact'),
        H2('How the two doors connect'),
        bullets([
            'CAS and STAR+PLUS HCBS cannot run at the same time. When HCBS starts, the caseworker ends CAS the day before MCO enrollment and the MCO re-authorizes the hours (CCSE 6430). Watch for a gap and call the Managed Care Helpline at 866-566-8989 if hours lapse.',
            'The same Form H2060 assessment tool is used by both, but only HCBS drops the 50-hour cap and the 24-point minimum (Form H2060 instructions; PSU Handbook 4200).',
            'The CDS employer accounts, the FMSA and the hired attendants can carry over; the MCO must give CDS information within 5 business days of a request (STAR+PLUS Handbook 8200).',
            'Both spouses can be on both programs. Each gets a separate assessment and separate hours; shared housekeeping, shopping and meal-prep minutes are scored on the "companion" range but hands-on personal care is not reduced (CCSE 2441.3).',
        ]),
    ]

def aunt_uncle_steps():
    return [
        PageBreak(), H1('3. Aunt and uncle: itemized steps'),
        P('These steps are for the aunt and uncle, done with the organizer\'s help. Where a step says "each," do it twice, once per spouse, and keep two files. '
          'If either of them cannot manage paperwork, they sign HHSC <b>Form H1003</b> (Appointment of an Authorized Representative) so the organizer can speak to HHSC. '
          'That is different from a CDS Designated Representative; see the warning at Step 14.'),
        H2('Phase A: This week (Days 1 to 7)'),
        steps_table([
            (1, 'Get on the STAR+PLUS HCBS interest list, each spouse.',
             'YourTexasBenefits.com > create account > "Find Support Services" referral; AND call HHSC at <b>844-438-5658</b> (fallback <b>877-438-5658</b>). Say: "Please add [name] to the STAR+PLUS HCBS interest list and give me the request date and confirmation." Rule: 1 TAC 353.1153(b).',
             'Day 1. Request date sets your place in line. Write it down.'),
            (2, 'Open a Community Care intake for each spouse and ask for Community Attendant Services with CDS.',
             'Call <b>2-1-1, option 2</b> (or <b>877-541-7905</b>). Say: "We want to apply for Community Attendant Services for two people in one home and be screened for every Community Care program. Please open a Form 2110 intake for each and note we want the Consumer Directed Services option." Ask for the regional CCSE office phone number.',
             'Day 1. Home visit is due within 14 calendar days (26 TAC 271.151).'),
            (3, 'File the Medicaid financial application, each spouse.',
             'Form <b>H1200</b> at YourTexasBenefits.com (or paper from the caseworker; fax 877-477-2839). On the same application, check Medicare Savings Programs (QMB/SLMB) so Medicaid pays the $202.90 Part B premium for each spouse if eligible. Ask for a Form H1800 receipt to prove the filing date. If the couple holds well over $3,000 in countable assets, read Section 6.2 on staging the two applications before filing the second one.',
             'Day 1 to 3. MEPD decision clock: 45 days (MEPD B-6400).'),
            (4, 'Doctor visit, each spouse: get Form 3052 signed and the chart to say what they cannot do.',
             'Ask the primary-care practitioner (MD, NP or PA) to complete <b>Form 3052</b> Practitioner\'s Statement of Medical Need, naming the medical conditions that cause limits in bathing, dressing, toileting, transfers, walking, eating, medications, memory. Ask for a copy of the visit note. A mental-illness or dementia diagnosis alone is not enough; a physical condition causing the limitation must be documented.',
             'Days 1 to 7. Provider must return a corrected 3052 within 5 business days when asked.'),
            (5, 'Get countable resources under the limit before the certification month.',
             'Limits: $2,000 (one applicant) or $3,000 (both) on the first day of the month. Exempt: the home (equity to $752,000), one vehicle, household goods, irrevocable prepaid funeral, term life. Legitimate spend-down: pay off debts, prepay funeral, home repairs, medical equipment. <b>Do not gift money or add anyone to the deed</b> (60-month look-back, MEPD Chapter I).',
             'Before the month you want coverage to start.'),
            (6, 'If income is over $2,982 a month for either spouse, set up a Qualified Income Trust (Miller trust).',
             'An elder-law attorney or the free Legal Hotline for Texans (<b>800-622-2520</b>, age 60+) can help; HHSC has a QIT template in the MEPD Handbook (Appendix XXXVI). Keep any VA Aid and Attendance out of the trust; it is not counted as income (MEPD E-4300).',
             'Same week; MEPD cannot certify until the trust exists.'),
            (7, 'Sign the legal documents while both are clearly competent.',
             'Statutory Durable Power of Attorney, Medical Power of Attorney, HIPAA release, Directive to Physicians, and consider a Transfer on Death Deed for the home. Free Texas forms at TexasLawHelp.org. Have them notarized.',
             'This week. Costs $0 to $30 for notary.'),
            (8, 'If either spouse is a veteran or the widow(er) of one, start the VA claim.',
             'Texas Veterans Commission claims counselor <b>800-252-8387</b> (free), or the VA benefits line <b>800-827-1000</b>. Ask for "Pension with Aid and Attendance" (Form 21P-527EZ plus 21-2680 exam form). See Section 5 and Section 6.',
             'This week; VA takes months, so start now.'),
        ]),
        H2('Phase B: The assessment visit (Days 7 to 21)'),
        steps_table([
            (9, 'Be home for the caseworker\'s visit; have the cousin present as informant.',
             'The caseworker scores each spouse on <b>Form H2060</b> (0 to 3 per task) and converts minutes per task into weekly hours. Answer for the <b>worst</b> days. Cover every task: bathing, dressing, grooming, toileting, transfers, walking, feeding, meal prep (all meals, 7 days), medications, laundry, cleaning, shopping, escort to appointments.',
             'Within 14 days of the intake. The visit sets the hours.'),
            (10, 'Make sure no needed task is coded "C" (caregiver does it free).',
             'The service-arrangement column decides what is purchased. State clearly: "Our niece will be the paid attendant; she will not be doing these tasks unpaid." Ask that minutes be set at the top of the range the impairment score allows. Score needed: 24+ for CAS. Living with another Community Care recipient waives the 6-hour minimum (26 TAC 271.81).',
             'At the visit.'),
            (11, 'Ask about "priority status" only for safety, never for hours.',
             'Priority status (cannot transfer, eat, toilet or cook without hands-on help and no one else is present) <b>lowers</b> the cap from 50 to 42 hours. With live-in caregivers you almost never want it.',
             'At the visit.'),
            (12, 'Ask the caseworker for the add-ons.',
             'Home-Delivered Meals (score 20+, no means test, Title XX), Day Activity and Health Services if useful, Emergency Response Services if the caregivers will be out 8+ hours a day. Also ask to be placed on the regional Family Care interest list the same day as a backup (request date controls, 26 TAC 271.5).',
             'At the visit.'),
            (13, 'Choose the Consumer Directed Services option, and get the "primary caregiver" question answered.',
             'The caseworker must present Forms <b>1581, 1582, 1583, 1584</b>. Elect CDS on <b>Form 1584</b> and pick an FMSA (both spouses can use the same FMSA; each is a separate employer). Sign Forms <b>1735</b> (employer-FMSA agreement), <b>1736</b> (orientation) and <b>1740</b> (backup plan naming the other caregiver). Form 1726 says the "primary caregiver" in PHC/CAS/FC cannot be the paid attendant; tell the caseworker in writing that the niece is a hired attendant, not the household\'s unpaid caregiver, and ask them to confirm she is an eligible hire (Section 4).',
             'At the visit or within days after.'),
            (14, '<b>Do NOT name the cousin or her husband as Designated Representative.</b>',
             'Form 1726: the DR and the DR\'s spouse cannot be paid employees of that member. If the aunt or uncle cannot handle employer duties even with FMSA support consultation (Form 1586), pick a different adult (a friend, another relative who lives elsewhere) as DR on Form 1720.',
             'Decide before signing CDS forms.'),
        ]),
        H2('Phase C: Approval and start of pay (Days 21 to 70)'),
        steps_table([
            (15, 'Watch for the eligibility notice and check the hours.',
             '<b>Form 2065-A</b> arrives within 2 business days of the decision (decision due within 30 days of the signed application). It lists weekly hours and appeal rights. Ask the caseworker for the Form H2060 worksheet. Form <b>2101</b> (authorization) goes to the FMSA within 5 business days.',
             'By about Day 30 to 45.'),
            (16, 'If hours look low, appeal immediately.',
             'Request a fair hearing by the deadline printed on Form 2065-A (generally 90 days), cite 26 TAC 271.81 and the Task/Hour Guide, and ask for a reassessment after any hospitalization, fall or decline. Benefits continue during a timely appeal of a reduction.',
             'Within the deadline on the notice.'),
            (17, 'Set the wage as high as the budget allows.',
             'Ask the FMSA for the written budget: rate $16.33/hour (Level 1) minus FMSA fee minus employer payroll taxes. Set the hourly wage on <b>Form 1730</b> at the maximum sustainable level; put any remainder into paid leave, holiday pay or bonuses (26 TAC 264.505). The old $10.60 wage floor was repealed Aug. 31, 2025, so nothing but the budget limits the wage.',
             'Before the first payroll.'),
            (18, 'Approve timesheets and EVV visits every pay period.',
             'The employer (or DR) approves hours the attendant clocked through the FMSA\'s Electronic Visit Verification app. Unapproved or unclocked visits do not get paid.',
             'Every pay period, forever.'),
            (19, 'Report changes to MEPD within 10 days and do the annual renewal.',
             'Income or resource changes, hospital stays over 30 days, address changes. Annual reassessment of hours (CCSE 2660) and annual MEPD redetermination.',
             'Ongoing.'),
        ]),
        H2('Phase D: When the STAR+PLUS HCBS interest list releases (Months 3 to 12)'),
        steps_table([
            (20, 'Answer every HHSC call and letter.',
             'HHSC contacts you annually to confirm interest; if they cannot reach you they mail <b>Form H2118</b>. Respond within 30 days or you are removed. In FY 2026-27, 7,466 people (44.6% of closures) were dropped for "no response."',
             'Whenever contacted.'),
            (21, 'Return the release packet within 30 days.',
             'The enrollment broker mails Form H1200 (again), <b>Form H2053-B</b> (health-plan choice) and the plan comparison chart within 7 days of confirming interest. Choose the MCO for your county after calling each plan\'s service-coordination line to ask about CDS and FMSAs. Missing 30 days means a default plan assignment.',
             '30 days from the packet date.'),
            (22, 'Get the MN/LOC and the new H2060 done fast.',
             'The MCO has 45 days to send a nurse for the Medical Necessity/Level of Care assessment (physician signature required), complete Form H2060 and write the Individual Service Plan (Form H1700-1). Ask for: attendant hours with no cap, <b>protective supervision</b> hours if there is memory impairment, 30 days of in-home respite (the respite worker must be someone who does not live in the home), ERS, adaptive aids, minor home modifications, dental.',
             'Within 45 days of release (STAR+PLUS PSU Handbook 3311).'),
            (23, 'Move the CDS employer accounts over.',
             'Tell the service coordinator you already use CDS and name your FMSA (it must contract with the new MCO; if not, choose another). Re-sign Forms 1584/1735 for the HCBS program. Start of care is the first day of the month after the last approval.',
             'Realistically 3 to 5 months from release.'),
            (24, 'Read the approval notice and calendar the renewal.',
             '<b>Form H2065-D</b> gives the start-of-care date, hours and appeal rights. The ISP and MN/LOC renew every 12 months. Request a change-of-condition reassessment after any decline.',
             'Every 12 months.'),
        ]),
    ]
